server:
    port: 8080

config:
    type: aws-parameterstore:/config/pumping

spring:
    config:
        import: ${config.type}

mongodb:
    database: pumping
    uri: ${.mongo.uri}
    username: ${.mongo.username}
    password: ${.mongo.password}

security:
    jwt:
        access:
            expire-length: ${.access-token.expire-length}
            secret-key: ${.access-token.secret}
            
oauth2:
    apple:
        iss: ${.apple.iss}
        client-id: ${.apple.client-id}
