server:
    port: 8080

spring:
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017
            username: admin
            password: password
            database: pumping

security:
  jwt:
    access:
      expire-length: ${.access-token.expire-length}
      secret-key: ${.access-token.secret}

oauth2:
  apple:
    iss: ${.apple.iss}
    client-id: ${.apple.client-id}
    
