spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

security:
  jwt:
    access:
      expire-length: 1000
      secret-key: secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet1

oauth2:
  apple:
    iss: iss
    client-id: client-id
