server:
    port: 8080

config:
  type: aws-parameterstore:/config/pumping

spring:
  config:
    import: ${config.type}

mongodb:
  database: pumping
  uri: ${.mongo.uri}
  username: ${.mongo.username}
  password: ${.mongo.password}
