server:
    port: 8080

config:
  type: aws-parameterstore:/config/pumping

spring:
  config:
    import: ${config.type}

mongodb:
  database: pumping
  uri: ${.mongo.uri}
  username: ${.mongo.username}
  password: ${.mongo.password}

security:
  jwt:
    access:
      expire-length: 1000
      secret-key: secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet1

oauth2:
  apple:
    iss: iss
    client-id: client-id
