server:
    port: 8080

spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/test

security:
    jwt:
        access:
            expire-length: 604800000
            secret-key: secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet1

oauth2:
    apple:
        iss: https://appleid.apple.com
        client-id: com.depromeet.pumping
