server:
    port: 8080
spring:
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017
            database: pumping
security:
    jwt:
        access:
            expire-length: 1000
            secret-key: secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet132secretk12342secrtet1
<<<<<<< HEAD
=======

>>>>>>> origin/feature/48
oauth2:
    apple:
        iss: iss
        client-id: client-id
