name: Github Action for NCP SSH
on:
    push:
        branches:
            - deploy
            - ci/*
jobs:
    ncp-direct-deploy:
        name: NCP-DIRECT-DEPLOY
        runs-on: ubuntu-latest
        steps:
            - name: Executing remote ssh commands using password
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.NCP_HOST_IP }}
                  username: ${{ secrets.NCP_USERNAME }}
                  password: ${{ secrets.NCP_PASSWORD }}
                  port: ${{ secrets.NCP_PORT }}
                  script: |
                      whoami
                      echo "Action runtime history: $(date)" >> /root/history.txt
                      cd /root/pumping-server
                      git fetch --all
                      git reset --hard origin/deploy
                      kill -9 $(sudo lsof -t -i:8080)
                      cd /root/pumping-server/pumping
                      mkdir -p /root/pumping-server/pumping/src/resources
                      echo "${{ secrets.APPLICATION }}" > /root/pumping-server/pumping/src/resources/application.properties
                      make ncp-deploy
    ci:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - name: Display branch name and commit hash
              run: |
                  echo "Current branch: ${{ github.ref }}"
                  echo "Commit hash: ${{ github.sha }}"
